# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sync.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('file', models.FileField(storage=sync.models.MediaFileSystemStorage(), upload_to=sync.models.user_directory_path, verbose_name='File')),
                ('hash', models.CharField(max_length=36)),
                ('date', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=36)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
